### PR TITLE
Add validation messages

### PR DESCRIPTION
**Pull request by Emmelie83**
Added validation messages for missing title and missing director.

### CODE REVIEW

**Review by Mattan41 — COMMENTED** [review]
I get 500 Internal server error and message ARJUNA016053: Could not commit transaction. when trying to post a movie withtout title or director, does this work for anyone else?

**Comment by Emmelie83** [comment]
To me it looks like this:
Screenshot 2024-03-06 215154

**Comment by Emmelie83** [comment]
Have you restarted Docker? I always have to restart Docker after making changes. Then I have to recreate the database table.

**Review by Mattan41 — APPROVED** [review]
Works after rebuilding the docker image and container.

**Pull request merged**
