### PR TITLE
Delete method in movieResource

### PR DESCRIPTION
**Pull request by Mattan41**
add the delete method in movieResource that mysteriosly dissapeared in the merge of delete-by-uuid

### CODE REVIEW

**Comment by Emmelie83** [comment]
Jag får inte detta att funka. Får felmeddelandet Method not allowed.

**Comment by Mattan41** [comment]
Får du method not allowed i postman? Vi kan nog skippa den här PR om vi godkänner exceptionMapper som också har deltemetoden, i uppdaterat format.  Är det samma för dig  i den?

**Comment by Emmelie83** [comment]
This is wrong in the deleteByUuid method in the Repository class: Movie movie = entityManager.find(Movie.class,uuid); 
The entitymanager.find method can only be used with the primary key.

**Comment by Mattan41** [comment]
yes should use findByUuid() instead. 
I am closing this PR in favour of the updated code in PR exceptionmapper .

**Pull request closed without merging**
